### ISSUE TITLE
[BUG]: Incompatible with Puppeteer 19

### ISSUE THREAD

**Issue by lubuzzo** [IBMa/equal-access#1319]
### Project

a11y checker

### Browser

Chrome

### Operating system

Other

### Description

I've tried to use this package with the latest Puppeteer release (19.7.2) and I got the following error:

```bash
TypeError: Cannot convert undefined or null to object
    at t.clearCaches (/tmp/accessibility-checker/engine/ace-node.js:2:474268)
    at e.run (/tmp/accessibility-checker/engine/ace-node.js:2:168661)
    at e.check (/tmp/accessibility-checker/engine/ace-node.js:2:194596)
    at /home/buzzo/web/ace-with-puppeteer/node_modules/accessibility-checker/lib/ACHelper.js:475:52
    at step (/home/buzzo/web/ace-with-puppeteer/node_modules/accessibility-checker/lib/ACHelper.js:33:23)
    at Object.next (/home/buzzo/web/ace-with-puppeteer/node_modules/accessibility-checker/lib/ACHelper.js:14:53)
    at /home/buzzo/web/ace-with-puppeteer/node_modules/accessibility-checker/lib/ACHelper.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/buzzo/web/ace-with-puppeteer/node_modules/accessibility-checker/lib/ACHelper.js:4:12)
    at getComplianceHelperLocal (/home/buzzo/web/ace-with-puppeteer/node_modules/accessibility-checker/lib/ACHelper.js:466:12)
    at /home/buzzo/web/ace-with-puppeteer/node_modules/accessibility-checker/lib/ACHelper.js:289:42
    at step (/home/buzzo/web/ace-with-puppeteer/node_modules/accessibility-checker/lib/ACHelper.js:33:23)
    at Object.next (/home/buzzo/web/ace-with-puppeteer/node_modules/accessibility-checker/lib/ACHelper.js:14:53)
    at fulfilled (/home/buzzo/web/ace-with-puppeteer/node_modules/accessibility-checker/lib/ACHelper.js:5:58)
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
```

However, when I try the latest 18 Puppeteer version (18.2.1) it works perfectly.

### Steps to reproduce

package.json
```json
{
  "name": "ace-with-puppeteer",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "accessibility-checker": "*",
    "puppeteer": "^19.7.2"
  }
}
```

main.js file:
```js
const puppeteer = require('puppeteer');
const achecker = require('accessibility-checker');

async function main() {
  browser = await puppeteer.launch();
  page = await browser.newPage();

  await page.goto('https://www.google.com.br');

  const result = await achecker.getCompliance(page, "Google");
  
  console.log(result);
};

main()
```

**Comment by aliunwala** [comment]
Triage:
Thanks for this report. We were able to reproduce the same thing. We will add this to our backlog and add it to a later sprint.

**Comment by tombrunet** [comment]
Latest is now 20, so PR #1454 updates to 20.

**Comment by tombrunet** [comment]
Moved back to in progress to update boilerplates.

**Comment by tombrunet** [comment]
See [4.0.0-rc.0](https://www.npmjs.com/package/accessibility-checker/v/4.0.0-rc.0) for Puppeteer 20 support. If you encounter issues with this version, please open new issues. Thank you.
