### ISSUE TITLE
[BUG] network error causes tests to fail

### ISSUE THREAD

**Issue by tay1orjones** [IBMa/equal-access#143]
## What tool(s) are you using?

- [ ] `accessibility-checker-engine`
- [x] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`
- [ ] `other`

## Detailed description

> Node version: 12.17.0
> Platform: mac
> Issue is present in v3.0.5 and v3.0.6

Related to https://github.com/IBMa/equal-access/pull/103, https://github.com/IBMa/equal-access/issues/102

> Describe in detail the issue you're having.

The following error is output when our builds fail in `carbon-addons-iot-react`
```
undefined:2
<!DOCTYPE html>
^
SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/accessibility-checker/lib/ACConfigLoader.js:112:38)
    at Request.self.callback (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/accessibility-checker/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/accessibility-checker/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/accessibility-checker/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Additionally, once I've added the mitigations present in Carbonhttps://github.com/carbon-design-system/carbon/blob/master/tasks/jest/matchers/toHaveNoDAPViolations.js#L10 and ibm-security https://github.com/carbon-design-system/ibm-security/pull/581 packages, our normal tests will pass, but our a11y tests using this package fail with the similar error:

```
Jest encountered an unexpected token
      
      This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
      
      By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
      
      Here's what you can do:
       • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
       • If you need a custom transformation specify a "transform" option in your config.
       • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
      
      You'll find more details and examples of these config options in the docs:
      https://jestjs.io/docs/en/configuration.html
      
      Details:
      
      /Users/taylorjones/dev/carbon-addons-iot-react/node_modules/accessibility-checker/lib/engine/ace-node.js:2
      <!DOCTYPE html>
      ^
      
      SyntaxError: Unexpected token '<'
          at compileFunction (<anonymous>)
          at compileFunction (vm.js:381:18)
          at Runtime._execModule (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/jest-runtime/build/index.js:1159:58)
          at Runtime._loadModule (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/jest-runtime/build/index.js:807:12)
          at Runtime.requireModule (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/jest-runtime/build/index.js:664:10)
          at Runtime.requireModuleOrMock (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/jest-runtime/build/index.js:828:21)
          at /Users/taylorjones/dev/carbon-addons-iot-react/node_modules/accessibility-checker/lib/ACHelper.js:301:31
          at /Users/taylorjones/dev/carbon-addons-iot-react/node_modules/jest-runner/node_modules/graceful-fs/graceful-fs.js:61:14
          at FSReqCallback.oncomplete (fs.js:155:23)

      at node_modules/accessibility-checker/lib/ACHelper.js:303:33

    console.error
      TypeError: ace.Checker is not a constructor
          at Object.aChecker.getComplianceHelperLocal (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/accessibility-checker/lib/ACHelper.js:655:27)
          at Object.aChecker.getComplianceHelper (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/accessibility-checker/lib/ACHelper.js:476:35)

      at Object.aChecker.getComplianceHelperLocal (node_modules/accessibility-checker/lib/ACHelper.js:706:21)
      at Object.aChecker.getComplianceHelper (node_modules/accessibility-checker/lib/ACHelper.js:476:35)

    console.error
      TypeError: ace.Checker is not a constructor
          at Object.aChecker.getComplianceHelperLocal (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/accessibility-checker/lib/ACHelper.js:655:27)
          at Object.aChecker.getComplianceHelper (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/accessibility-checker/lib/ACHelper.js:476:35)

      at Object.aChecker.getComplianceHelperLocal (node_modules/accessibility-checker/lib/ACHelper.js:706:21)
      at Object.aChecker.getComplianceHelper (node_modules/accessibility-checker/lib/ACHelper.js:476:35)

    console.error
      TypeError: ace.Checker is not a constructor
          at Object.aChecker.getComplianceHelperLocal (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/accessibility-checker/lib/ACHelper.js:655:27)
          at Object.aChecker.getComplianceHelper (/Users/taylorjones/dev/carbon-addons-iot-react/node_modules/accessibility-checker/lib/ACHelper.js:476:35)

      at Object.aChecker.getComplianceHelperLocal (node_modules/accessibility-checker/lib/ACHelper.js:706:21)
      at Object.aChecker.getComplianceHelper (node_modules/accessibility-checker/lib/ACHelper.js:476:35)
```

**Comment by tombrunet** [comment]
@tay1orjones Are you seeing this issue frequently?

We can look into making the error message more clear, and perhaps add some retries. However, if you're looking for the tool to not pull from the network at all, that's going to require a bit more thought.

At the moment, we pull the engine and the rules from a content server. Two major reasons for this:
* When we first created this set of tools, we had a lot of confusion with earlier tools with keeping in sync across teams. Two people on the same team would see different results because there were on different fixpacks. This is amplified when people are identifying an issue with an automated tool, and then investigating it with a browser extension. Some of the tool users aren't highly technical, so we do our best to be able to focus on rulepack (or latest by default), and not have to worry about what version of the tool you have installed.
* We ran into issues with Selenium environments. Basically, the only option to load the rules was to pull them from a server.

Given than, I'm trying to understand how best to sort this out. How often are you hitting this issue? We haven't run into network issues with the ruleserver, aside from a couple of massive network DNS outages - like the recent cloudflare one that knocked out NPM also. If we can identify where the failure is, it would help in not seeing this type of error at all

**Comment by tay1orjones** [comment]
@tombrunet This is the first time we've seen this error since upgrading to the new `accessibility-checker` package on June 25th.

I definitely see your point on why to pull from a centralized toolset via the network. If the error message was more descriptive, we'd have more confidence in bypassing a11y status checks for our PRs if/when we run into network issues again. 

Retries may not be worth the investment, in our case the outage/problem was prolonged. We restarted the failing builds occasionally throughout the work day and they continued to fail.

**Comment by tombrunet** [comment]
This seems to have only been reported during the major internet outage due to cloudflare issues. Does not appear to be a regular issue.
